export const CURRENTUSER = 'CURRENTUSER';
export const VERIFYUSER = 'VERIFYUSER';
export const LOGOUTUSER = 'LOGOUTUSER';
export const MEESSAGEFROMSERVER = 'MEESSAGEFROMSERVER';
export const USERNUMBER = 'USERNUMBER';
